name: Update TSLA Stock Info

on:
  schedule:
    - cron: '*/3 * * * *'  # 매일 12시 (KST)
  workflow_dispatch:

jobs:
  update-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run script
        working-directory: ./api
        run: python update_stock.py
